name: CDgitops

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    run-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/cd-gitops
          tags: latest, ${{ github.sha }}
        run: |
          echo "Build"